/**
 * Which grades a teacher may create a class in.
 *
 * ── The bug this exists for ────────────────────────────────────────────────
 *
 * "បង្កើតថ្នាក់ថ្មី" offered exactly the `grades` rows the school happened to hold.
 * `seedEducationLevel` writes the level's whole range (1–6 for បឋមសិក្សា), so a
 * school created through the current wizard has all six — but a school seeded
 * by an older path, or one whose seeding upsert failed, holds one row, and the
 * dialog then offers one grade with no way to add another. Nothing in the
 * teacher app creates a grade: `/admin/classes` needs a principal, and the
 * wizard's level step runs once. The teacher is simply stuck.
 *
 * So the offer is derived from the **curriculum**, not from the rows: every
 * grade `EDUCATION_LEVELS` defines for a level the school has, with the
 * existing rows matched into it by grade number. A grade with no row yet is
 * offered anyway and its row is created when a class is actually put in it
 * (`ensureGrade`), so nothing is written for a grade nobody uses.
 *
 * ── Why match on the number, not the name ──────────────────────────────────
 *
 * `grades.name` is `ថ្នាក់ទី៥` — Khmer numerals, generated by `gradeName()`. A
 * name comparison would break on any school whose rows were typed by hand or
 * written by an older generator, and would then offer a *duplicate* of a grade
 * that already exists. `sort_order` is the grade number by construction
 * (`gradesForLevel` sets it from the range), and `UNIQUE (education_level_id,
 * name)` makes the eventual insert safe either way.
 *
 * Pure and free of server-only imports: the page resolves it on the server and
 * the dialog reads the result, and `scripts/verify-classroom.mts` runs it under
 * plain `node`.
 */

import { EDUCATION_LEVELS, gradeName, levelByName } from '../onboarding/curriculum.ts'

/** An `education_levels` row, as the classroom page reads it. */
export interface SchoolLevelRow {
  id: string
  name: string
}

/** A `grades` row, as the classroom page reads it. */
export interface SchoolGradeRow {
  id: string
  name: string
  sort_order: number | null
  education_level_id: string
}

/** One grade the create dialog may offer. */
export interface GradeOption {
  /**
   * The `grades.id`, or `null` when the curriculum defines this grade but the
   * school has no row for it yet. A null id is not an error state — it is a
   * grade nobody has taught here, and `ensureGrade` creates the row when
   * someone does.
   */
  id: string | null
  educationLevelId: string
  /** 1–12. `grades.sort_order`, and what `gradeName()` renders. */
  gradeNumber: number
  name: string
  levelName: string
}

/**
 * A stable value for the `<Select>`, since half the options have no id yet.
 *
 * Level id plus grade number rather than the name: two levels in one school can
 * both define a grade 1, and the name alone would collide.
 */
export function gradeOptionValue(option: GradeOption): string {
  return option.id ?? `new:${option.educationLevelId}:${option.gradeNumber}`
}

/**
 * The full grade offer for a school: every grade its levels' curricula define,
 * carrying the existing row's id where there is one.
 *
 * A level the school holds that `EDUCATION_LEVELS` does not recognise still
 * contributes its own rows — an unknown level name must not silently delete a
 * grade a teacher is already using.
 */
export function buildGradeOffer(
  levels: SchoolLevelRow[],
  grades: SchoolGradeRow[],
): GradeOption[] {
  const rowsByLevel = new Map<string, SchoolGradeRow[]>()
  for (const row of grades) {
    const list = rowsByLevel.get(row.education_level_id) ?? []
    list.push(row)
    rowsByLevel.set(row.education_level_id, list)
  }

  const out: GradeOption[] = []

  for (const level of levels) {
    const rows = rowsByLevel.get(level.id) ?? []
    const spec = levelByName(level.name)

    if (!spec) {
      // An unrecognised level: offer exactly what it holds, in its own order.
      for (const row of [...rows].sort((a, b) => (a.sort_order ?? 0) - (b.sort_order ?? 0))) {
        out.push({
          id: row.id,
          educationLevelId: level.id,
          gradeNumber: row.sort_order ?? 0,
          name: row.name,
          levelName: level.name,
        })
      }
      continue
    }

    const byNumber = new Map(rows.map((r) => [r.sort_order ?? 0, r]))
    for (let n = spec.from; n <= spec.to; n++) {
      const row = byNumber.get(n)
      out.push({
        id: row?.id ?? null,
        educationLevelId: level.id,
        gradeNumber: n,
        // The stored name wins where a row exists, so the dialog and the class
        // list cannot disagree about what a grade is called.
        name: row?.name ?? gradeName(n),
        levelName: level.name,
      })
    }

    // A row outside the curriculum's range — a grade 7 filed under បឋមសិក្សា by
    // an old import, say. Kept, because a class may already sit in it.
    for (const row of rows) {
      const n = row.sort_order ?? 0
      if (n >= spec.from && n <= spec.to) continue
      out.push({
        id: row.id,
        educationLevelId: level.id,
        gradeNumber: n,
        name: row.name,
        levelName: level.name,
      })
    }
  }

  // Level order first (បឋមសិក្សា before មធ្យមសិក្សា), then grade number — the order a
  // Cambodian teacher reads a ladder in. An unrecognised level sorts last
  // rather than to the front, which is where `findIndex`'s -1 would put it.
  const levelRank = (name: string) => {
    const i = EDUCATION_LEVELS.findIndex((l) => l.name === name)
    return i === -1 ? Number.MAX_SAFE_INTEGER : i
  }

  return out.sort(
    (a, b) => levelRank(a.levelName) - levelRank(b.levelName) || a.gradeNumber - b.gradeNumber,
  )
}
